### PR TITLE
guidelines: add rule about ordering of comments

### PR DESCRIPTION
**Pull request by ErikSchierboom**

### CODE REVIEW

**Comment by SleeplessByte** [comment]
I understand this rule, in line with #49, but sometimes it might make sense to order the comments in terms of _structural_ order. Now that I think about it, usually this is the order of importance, but not always. 

e.g. you might want to say something about a `mapper`, which is very important and give a tip about using functions as first class citizens with that mapper. The latter might be a tip. It makes more sense to have these "two-gether" then to put the tip at the bottom (requiring the student to revisit something they might already have changed).

**Comment by ErikSchierboom** [comment]
That makes sense. Do you have a suggestion for a better wording?

**Comment by SleeplessByte** [comment]
Not yet. 

Perhaps something like, "you **MAY** group less important comments with an important comment, in spite of ordering, if they're about the same subject."

**Comment by ErikSchierboom** [comment]
Yeah, something like that would be nice. But I'm not sure about the `group less important comments` part. We're not really grouping comments, we're only ordering them. @iHiD any ideas?

**Comment by iHiD** [comment]
I'm :+1: on this because I think it's a good rule for now. This whole area is going to need some serious product thinking (which we'll be starting in the next few weeks) and then I think we'll have a better idea. Until then, I don't feel like I know enough to really be useful. So I'd vote get this down on master for now, and then re-address it later when we refine our understanding.

**Pull request merged**
