### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by kmjones77**
slight change to text readability

### CODE REVIEW

**Review by ErikSchierboom — APPROVED** [review]

**Comment by ErikSchierboom** [comment]
Thanks!

**Comment by kmjones77** [comment]
No worries!

**Comment by iHiD** [comment]
Thanks @kmjones77! :) Great to have you here! Ping me on Slack at some point. And also tell Gaz to get involved :)

**Comment by kmjones77** [comment]
No worries @iHiD I'm really enjoying both solving and mentoring! I've spoken to Gareth, I'll mention it to him again! Would be good to catch up sometime and maybe get involved in V3!!!

**Comment by iHiD** [comment]
Definitely. If you're working in C#, @ErikSchierboom would love all the help he can get!

**Comment by ErikSchierboom** [comment]
Absolutely! Let me know if you'd like to help out with the C# track, and I'll get you up to speed :)

**Pull request merged**
